variables:
    GIT_SUBMODULE_STRATEGY: recursive

image: aeralpaca/alpaca_paco:latest

stages:
 - alltests

Unit tests:
  stage: alltests
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make Paco -j 4
    - mpiexec -n 1 ./Paco [1rank]
    - mpiexec -n 2 ./Paco [2rank]

Standard 1D Alpaca:
  stage: alltests
  script:
    - python3 Utilities/PythonScripts/prepare_user_settings_for_build.py . --limit-end-time
    - mkdir build
    - cd build
    - cmake -DDIM=1 ..
    - make -j 2
    - mv ALPACA ../A_1D_STD
    - cd ..
    - mpiexec -n 1 ./A_1D_STD Utilities/Inputfiles/CiCd/1D-LevelsetSodX.xml
    - mpiexec -n 2 ./A_1D_STD Utilities/Inputfiles/CiCd/1D-LevelsetSodX.xml
    - python3 Utilities/PythonScripts/remove_volatile_strings_from_logfile.py 1D-LevelsetSodX/1D-LevelsetSodX.log
    - python3 Utilities/PythonScripts/remove_volatile_strings_from_logfile.py 1D-LevelsetSodX-1/1D-LevelsetSodX.log
    - diff 1D-LevelsetSodX/1D-LevelsetSodX.log 1D-LevelsetSodX-1/1D-LevelsetSodX.log
    - python3 Utilities/PythonScripts/sod_analysis.py 1D-LevelsetSodX/domain/data_2.000000.h5 0.20000000 --max-density-errors 5.0e-08 2.0e-5 3.0e-1 --max-velocity-errors 5.5e-08 2.5e-05 3.5e-01

Varied 1D Alpaca :
  stage: alltests
  script:
    - python3 Utilities/PythonScripts/prepare_user_settings_for_build.py . --ic 24 --riemann Hllc --reinit Min --limit-end-time
    - mkdir build
    - cd build
    - cmake -DDIM=1 ..
    - make -j 2
    - mv ALPACA ../A_1D_VAR
    - cd ..
    - mpiexec -n 1 ./A_1D_VAR Utilities/Inputfiles/CiCd/1D-LevelsetSodX.xml
    - mpiexec -n 2 ./A_1D_VAR Utilities/Inputfiles/CiCd/1D-LevelsetSodX.xml
    - python3 Utilities/PythonScripts/remove_volatile_strings_from_logfile.py 1D-LevelsetSodX/1D-LevelsetSodX.log
    - python3 Utilities/PythonScripts/remove_volatile_strings_from_logfile.py 1D-LevelsetSodX-1/1D-LevelsetSodX.log
    - diff 1D-LevelsetSodX/1D-LevelsetSodX.log 1D-LevelsetSodX-1/1D-LevelsetSodX.log
    - python3 Utilities/PythonScripts/sod_analysis.py 1D-LevelsetSodX-1/domain/data_2.000000.h5 0.20000000 --max-density-errors 2.0e-08 1.5e-05 5.5e-01 --max-velocity-errors 2.0e-08 1.5e-05 5.5e-1

Two dimensional Alpaca:
  stage: alltests
  script:
    - python3 Utilities/PythonScripts/prepare_user_settings_for_build.py . --axisymmetric --ic 20 --timeintegration RK2 --reconstructionstencil TENO5
    - mkdir build
    - cd build
    - cmake -DDIM=2 ..
    - make -j 2
    - mv ALPACA ../A_2D
    - cd ..
    - mpiexec -n 1 ./A_2D Utilities/Inputfiles/CiCd/2D-Dummy.xml
    - mpiexec -n 2 ./A_2D Utilities/Inputfiles/CiCd/2D-Dummy.xml
    - python3 Utilities/PythonScripts/remove_volatile_strings_from_logfile.py 2D-Dummy/2D-Dummy.log
    - python3 Utilities/PythonScripts/remove_volatile_strings_from_logfile.py 2D-Dummy-1/2D-Dummy.log
    - diff 2D-Dummy/2D-Dummy.log 2D-Dummy-1/2D-Dummy.log

Three dimensional Alpaca:
  stage: alltests
  script:
    - python3 Utilities/PythonScripts/prepare_user_settings_for_build.py . --gruneisen-density --lsadvect DerivativeStencil --interfaceriemann TwoRarefaction
    - mkdir build
    - cd build
    - cmake ..
    - make -j 2
    - mv ALPACA ../A_3D
    - cd ..
    - mpiexec -n 1 ./A_3D Utilities/Inputfiles/CiCd/3D-Dummy.xml
    - mpiexec -n 2 ./A_3D Utilities/Inputfiles/CiCd/3D-Dummy.xml
    - python3 Utilities/PythonScripts/remove_volatile_strings_from_logfile.py 3D-Dummy/3D-Dummy.log
    - python3 Utilities/PythonScripts/remove_volatile_strings_from_logfile.py 3D-Dummy-1/3D-Dummy.log
    - diff 3D-Dummy/3D-Dummy.log 3D-Dummy-1/3D-Dummy.log