MESSAGE( STATUS "Set performance flags" )

if( ALPACA_ENV STREQUAL "LRZ" )
   set( MACHINE_FLAGS "-D PERFORMANCE -fp-model precise" )
endif( ALPACA_ENV STREQUAL "LRZ" )

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${MACHINE_FLAGS}")